#!/usr/bin/ruby
# frozen_string_literal: true

# The above can be replaced with whatever language you choose

# Modify this file to create your hangman program.
#
# The input filename will come as an argument (see completeness_test).

require_relative "lib/game"

module Hangman
  module_function

  def run(input_filename)
    read_games(input_filename).each(&method(:play_game))
  end

  def play_game(game)
    guesses = game.split("\n")
    word = guesses.shift
    game = Game.new(guesses: Guesses.new(word: word))

    puts game.output

    guesses.each do |guess|
      game.play(guess: guess)
      puts game.output
    end
  end

  def read_games(input_filename)
    file_content = File.read(input_filename)
    file_content.split("\n\n")
  end

  def stdout_and_exit
    puts "ERROR: Expected input.txt file!\n\n"
    puts "Usage:\t./hangman input.txt\n\n"
    exit(1)
  end
end

if $PROGRAM_NAME == __FILE__
  input_filename = ARGV.first

  if input_filename.nil?
    Hangman.stdout_and_exit
  end

  Hangman.run(input_filename)
end
