#!/usr/bin/ruby
# frozen_string_literal: true

# The above can be replaced with whatever language you choose

# Modify this file to create your hangman program.
#
# The input filename will come as an argument (see completeness_test).
input_filename = ARGV[0]

def stdout_and_exit
  puts "ERROR: Expected input.txt file!\n\n"
  puts "Usage:\t./hangman input.txt\n\n"
  exit(1)
end

stdout_and_exit if input_filename.nil?

require_relative "lib/game"

file_content = File.read(input_filename)
games = file_content.split("\n\n")
games.each do |game|
  guesses = game.split("\n")
  word = guesses.shift

  game = Game.new(word: word)
  puts game.output

  guesses.each do |guess|
    game.play(guess: guess)
    puts game.output
  end
end
